image: openjdk:8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/endomie-0.0.1-SNAPSHOT.jar
      
Test:
  stage: test
  script: 
    - ./gradlew check
    - ./gradlew jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html


Deployment:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=e-ndomie --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
