image: gradle:4.6-jdk8-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew
  - git commit

stages:
  - test
  - deploy
    
Test:
  stage: test
  script: 
    - ./gradlew check
    - ./gradlew jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html


Deployment:
  stage: deploy
  image: ruby:2.3
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_API_KEY
  only:
  - master
