image: gradle:4.6-jdk8-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - git update-index --chmod=+x gradlew

stages:
  - test
  - deploy
  - build
  
build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - build/libs/myApp-4.0.0-SNAPSHOT.jar
      
unitTests:
  stage: test
  script:
    - ./gradlew test


Deployment:
  stage: deploy
  image: ruby:2.3
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_API_KEY
  only:
  - master
